spring.application.name=tourplannerbackend

jdbc:postgresql://postgres:5432/tourplanner
#spring.datasource.url=jdbc:postgresql://localhost:5432/tourplanner
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
