spring.application.name=tourplannerbackend

spring.datasource.url=jdbc:postgresql://postgres:5432/tourplanner
#spring.datasource.url=jdbc:postgresql://localhost:5432/tourplanner
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
# openapi
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#OpenRouteService
spring.config.import=optional:file:.env[.properties]
openrouteservice.key=${OPEN_ROUTE_SERVICE_API_KEY}
openrouteservice.baseUrl=https://api.openrouteservice.org